### ISSUE TITLE
rebase to upstream

### ISSUE THREAD

**Issue by p5-vbnekit** [ScriptedSnark/agmod-server-updated#5]
Hello! May you rebase (and/or send PR) to upstream - https://github.com/fireblizzard/agmod?

**Comment by ScriptedSnark** [comment]
Any reasons? I don't want to have some fixes/features from fireblizzard repo

**Comment by p5-vbnekit** [comment]
> I don't want to have some fixes/features from fireblizzard repo

As far as I understand, not all changes in upstream you consider unacceptable. I just would like to gather more useful features on my server. IMHO, most "live" forks of original `agmod` is your fork and your upstream.

Could you at least do a partial rebase/merge, removing those commits (or changes to them) that you think are not needed?
Or at least send your patches to your upstream maintainer please.

Thanks!

**Comment by ScriptedSnark** [comment]
You can fork my repository and add necessary commits, but I will consider your issue for a partial merge

**Comment by p5-vbnekit** [comment]
Ok. Thanks.
